### PR TITLE
Add ibc.mock proto definitions

### LINKED ISSUE #11: Add Protobuf definitions for mock client state

### PR DESCRIPTION
**Pull request by romac**
Close: #11 

Depends on: #9

---

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGES.md

### CODE REVIEW

**Comment by greg-szabo** [comment]
I think we should be careful with introducing custom proto files into the proto crate. The original thinking was that this crate is fully generated by a compiler.

With the current implementation, the proto files should be in the compiler folder. Or maybe we could revisit how we create proto structs.

**Comment by romac** [comment]
> With the current implementation, the proto files should be in the compiler folder.

I am not sure what you mean by that?

**Comment by romac** [comment]
> I think we should be careful with introducing custom proto files into the proto crate. The original thinking was that this crate is fully generated by a compiler.

I am not sure what you mean by that either.

By custom proto, do you mean the mock proto file this PR adds? Or the generated Rust code? If the latter, [we already package](https://github.com/informalsystems/ibc-proto/tree/master/ibc_proto/src/prost) the generated Rust code within the repository, no?

In any case, the Rust code is still fully generated by the ibc-prost-compiler, unless I am missing something?

**Comment by romac** [comment]
I agree that those `.proto` files should probably live in the `ibc-rs` repo, but until we move `ibc-proto` there I figured we could include them within this repo.

**Comment by greg-szabo** [comment]
Yes, the proto files are all right in this repo. The folder name “proto” distracted me. In Tendermint-rs, the folder name proto contains the Tendermint-proto crate. In IBC-rs, I’d like it the same. But if we have custom proto files, we’ll have to figure out what is best. For now, this is good as it is.

________________________________

**Review by greg-szabo — APPROVED** [review]

**Pull request merged**
